stages:
  - e2e

# - test
# - bundle
# - build

variables:
  DOCKER_DRIVER: overlay

e2e_tests:
  image: 0xacab.org:4567/leap/bitmask-dev:latest
  stage: e2e
  allow_failure: true
  script:
    - virtualenv venv
    - source venv/bin/activate
    - make dev-latest-backend
    - mkdir -p /root/.config/leap/
    - make install_helpers
    - make test_e2e
  tags:
    - linux

