name: riseup-vpn
version: '0.10.4'
epoch: 0
summary: RiseupVPN, anonymous VPN. Powered by Bitmask.
description: |
        RiseupVPN is an easy, fast, and secure VPN service from riseup.net.
        RiseupVPN does not require a user account, keep logs, or track you in
        any way. The service is paid for entirely by donations from users like
        you.

grade: stable # must be 'stable' to release into candidate/stable channels. switch to devel in snap branch.
confinement: classic
icon: snap/gui/riseupvpn.svg

parts:
         
        bitmask:
                plugin: python
                python-version: python2
                source-branch: master
                source: https://0xacab.org/leap/bitmask-dev.git
                requirements: pkg/requirements-vpn.pip
                stage-packages:
                        # this seems to trigger https://bugs.launchpad.net/snapcraft/+bug/1676684
                        - python2.7-dev
                        - libsqlcipher-dev
                        - libffi-dev
                        - libsqlite3-dev
                        - libzmq3-dev
                prime: 
                    - -usr/include
                    - -usr/lib/locale
                    - -usr/share/X11/locale
                    - -usr/share/doc
                    - -usr/share/locale
                    - -usr/share/man
                    #- -usr/share/icons
        openvpn:
                plugin: nil
                stage-packages:
                        - openvpn
                prime:
                    - -usr/share/doc
                    - -usr/share/man
        bitmask-systray:
                plugin: go
                source: https://0xacab.org/leap/bitmask-systray.git
                build-packages:
                        - pkg-config
                        - patchelf
                        - libzmq5
                        - libzmq3-dev
                        - libsodium-dev
                        - libappindicator3-dev
                        - libgtk-3-dev
                stage-packages:
                        - libzmq5
                        - libsodium18
                        - libappindicator3-1
                install: |
                  TRIPLET_PATH="$SNAPCRAFT_PART_INSTALL/usr/lib/$(gcc -print-multiarch)"
                  LIBZMQ=$(readlink -n $TRIPLET_PATH/libzmq.so.5)
                  LIBSOD=$(readlink -n $TRIPLET_PATH/libsodium.so.18)
                  ln -s "../usr/lib/$(gcc -print-multiarch)/$LIBZMQ" $SNAPCRAFT_PART_INSTALL/bin/libzmq.so.5
                  ln -s "../usr/lib/$(gcc -print-multiarch)/$LIBSOD" $SNAPCRAFT_PART_INSTALL/bin/libsodium.so.18
                  patchelf --set-rpath /snap/riseup-vpn/current/bin/ $SNAPCRAFT_PART_INSTALL/bin/bitmask-systray.git
                prime: 
                    - -usr/include
                    - -usr/lib/locale
                    - -usr/share/X11/locale
                    - -usr/share/doc
                    - -usr/share/locale
                    - -usr/share/man
                    #- -usr/share/icons
        desktop-gtk3:
                prime: 
                    - -usr/include
                    - -usr/lib/locale
                    - -usr/share/X11/locale
                    - -usr/share/doc
                    - -usr/share/locale
                    - -usr/share/man
                    #- -usr/share/icons
                    - '*'

apps:
        launcher:
                command: ./bin/bitmask_anonvpn
        openvpn:
                command: ./usr/sbin/openvpn
        bitmaskd:
                command: ./bin/bitmaskd
        bitmask-systray:
                command: ./bin/bitmask-systray.git
