name: riseup-vpn
version: '0.10.3+git'
epoch: 0
summary: RiseupVPN, anonymous VPN. Powered by Bitmask.
description: |
        RiseupVPN is an anonymous VPN. It's controlled by a minimal systray
        that communicates with the bitmask daemon.
        Just click on it. And don't forget to donate.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic
icon: snap/gui/riseupvpn.svg

parts:
         
        bitmask:
                plugin: python
                python-version: python2
                source-branch: snap 
                # XXX change to leap/master when merged
                source: https://0xacab.org/kali/bitmask-dev.git
                requirements: pkg/requirements-vpn.pip
                stage-packages:
                        # this seems to trigger https://bugs.launchpad.net/snapcraft/+bug/1676684
                        - python2.7-dev
                        - libsqlcipher-dev
                        - libffi-dev
                        - libsqlite3-dev
                        - libzmq3-dev
        openvpn:
                plugin: nil
                stage-packages:
                        - openvpn
                # TODO copy openvpn to /usr/local/sbin
        bitmask-systray:
                plugin: go
                source: https://0xacab.org/leap/bitmask-systray.git
                build-packages:
                        - pkg-config
                        - patchelf
                        - libzmq5
                        - libzmq3-dev
                        - libsodium-dev
                        - libappindicator3-dev
                        - libgtk-3-dev
                stage-packages:
                        - libzmq5
                        - libsodium18
                        - libappindicator3-1
                install: |
                  TRIPLET_PATH="$SNAPCRAFT_PART_INSTALL/usr/lib/$(gcc -print-multiarch)"
                  LIBZMQ=$(readlink -n $TRIPLET_PATH/libzmq.so.5)
                  LIBSOD=$(readlink -n $TRIPLET_PATH/libsodium.so.18)
                  ln -s "../usr/lib/$(gcc -print-multiarch)/$LIBZMQ" $SNAPCRAFT_PART_INSTALL/bin/libzmq.so.5
                  ln -s "../usr/lib/$(gcc -print-multiarch)/$LIBSOD" $SNAPCRAFT_PART_INSTALL/bin/libsodium.so.18
                  patchelf --set-rpath /snap/riseup-vpn/current/bin/ $SNAPCRAFT_PART_INSTALL/bin/bitmask-systray.git
        desktop-gtk3:
                prime: 
                    - -usr/include
                    - -usr/lib/locale
                    - -usr/share/X11/locale
                    - -usr/share/doc
                    - -usr/share/locale
                    - -usr/share/man
                    - -usr/share/icons
                    - '*'

apps:
        bitmask-systray:
                command: ./bin/bitmask-systray.git
        launcher:
                command: ./bin/bitmask_anonvpn
        bitmaskd:
                command: ./bin/bitmaskd
